"""initial_schema

Revision ID: 47d9f9f25c3e
Revises: 
Create Date: 2026-05-20 14:27:28.235037

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "47d9f9f25c3e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("entity_id", sa.String(), nullable=False),
        sa.Column("transaction_id", sa.String(), nullable=True),
        sa.Column("alert_type", sa.String(), nullable=True),
        sa.Column("typology", sa.String(), nullable=True),
        sa.Column("severity", sa.String(), nullable=True),
        sa.Column("risk_score", sa.Float(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("evidence", sa.JSON(), nullable=True),
        sa.Column("recommended_action", sa.String(), nullable=True),
        sa.Column("assigned_to", sa.String(), nullable=True),
        sa.Column("assigned_at", sa.DateTime(), nullable=True),
        sa.Column("resolved_by", sa.String(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("resolution", sa.String(), nullable=True),
        sa.Column("resolution_notes", sa.Text(), nullable=True),
        sa.Column("sar_required", sa.Boolean(), nullable=True),
        sa.Column("sar_filed", sa.Boolean(), nullable=True),
        sa.Column("sar_filed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cases",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("entity_id", sa.String(), nullable=False),
        sa.Column("alert_ids", sa.JSON(), nullable=True),
        sa.Column("case_type", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("assigned_to", sa.String(), nullable=True),
        sa.Column("assigned_at", sa.DateTime(), nullable=True),
        sa.Column("due_date", sa.DateTime(), nullable=True),
        sa.Column("investigator_notes", sa.Text(), nullable=True),
        sa.Column("evidence", sa.JSON(), nullable=True),
        sa.Column("timeline", sa.JSON(), nullable=True),
        sa.Column("sar_required", sa.Boolean(), nullable=True),
        sa.Column("sar_drafted", sa.Boolean(), nullable=True),
        sa.Column("sar_filed", sa.Boolean(), nullable=True),
        sa.Column("sar_reference", sa.String(), nullable=True),
        sa.Column("outcome", sa.String(), nullable=True),
        sa.Column("closed_by", sa.String(), nullable=True),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "entities",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("aliases", sa.JSON(), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("nationality", sa.String(length=3), nullable=True),
        sa.Column("occupation", sa.String(), nullable=True),
        sa.Column("employer", sa.String(), nullable=True),
        sa.Column("phones", sa.JSON(), nullable=True),
        sa.Column("emails", sa.JSON(), nullable=True),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("kyc_level", sa.String(), nullable=True),
        sa.Column("kyc_status", sa.String(), nullable=True),
        sa.Column("kyc_completed_at", sa.DateTime(), nullable=True),
        sa.Column("kyc_next_review", sa.DateTime(), nullable=True),
        sa.Column("income_verified", sa.Boolean(), nullable=True),
        sa.Column("source_of_wealth_verified", sa.Boolean(), nullable=True),
        sa.Column("edd_required", sa.Boolean(), nullable=True),
        sa.Column("risk_score", sa.Float(), nullable=True),
        sa.Column("fraud_score", sa.Float(), nullable=True),
        sa.Column("aml_score", sa.Float(), nullable=True),
        sa.Column("network_score", sa.Float(), nullable=True),
        sa.Column("risk_tier", sa.String(), nullable=True),
        sa.Column("aml_rating", sa.String(), nullable=True),
        sa.Column("expected_monthly_inflow", sa.Float(), nullable=True),
        sa.Column("expected_monthly_outflow", sa.Float(), nullable=True),
        sa.Column("sars_filed", sa.Integer(), nullable=True),
        sa.Column("typology_matches", sa.JSON(), nullable=True),
        sa.Column("avg_transaction_amount", sa.Float(), nullable=True),
        sa.Column("typical_hours", sa.String(), nullable=True),
        sa.Column("typical_locations", sa.JSON(), nullable=True),
        sa.Column("device_count", sa.Integer(), nullable=True),
        sa.Column("last_anomaly_at", sa.DateTime(), nullable=True),
        sa.Column("is_pep", sa.Boolean(), nullable=True),
        sa.Column("is_sanctioned", sa.Boolean(), nullable=True),
        sa.Column("adverse_media_hits", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "identity_documents",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("entity_id", sa.String(), nullable=False),
        sa.Column("doc_type", sa.String(), nullable=True),
        sa.Column("doc_number_hash", sa.String(), nullable=True),
        sa.Column("issuing_country", sa.String(), nullable=True),
        sa.Column("issuing_state", sa.String(), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=True),
        sa.Column("verified_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("entity_id", sa.String(), nullable=False),
        sa.Column("account_id", sa.String(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("txn_type", sa.String(), nullable=True),
        sa.Column("direction", sa.String(), nullable=True),
        sa.Column("channel", sa.String(), nullable=True),
        sa.Column("counterparty_name", sa.String(), nullable=True),
        sa.Column("counterparty_account", sa.String(), nullable=True),
        sa.Column("counterparty_bank", sa.String(), nullable=True),
        sa.Column("counterparty_country", sa.String(), nullable=True),
        sa.Column("merchant_name", sa.String(), nullable=True),
        sa.Column("merchant_category", sa.String(), nullable=True),
        sa.Column("location_city", sa.String(), nullable=True),
        sa.Column("location_country", sa.String(), nullable=True),
        sa.Column("risk_score", sa.Float(), nullable=True),
        sa.Column("is_flagged", sa.Boolean(), nullable=True),
        sa.Column("flag_reasons", sa.JSON(), nullable=True),
        sa.Column("rule_hits", sa.JSON(), nullable=True),
        sa.Column("ml_score", sa.Float(), nullable=True),
        sa.Column("txn_timestamp", sa.DateTime(), nullable=False),
        sa.Column(
            "processed_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transactions")
    op.drop_table("identity_documents")
    op.drop_table("entities")
    op.drop_table("cases")
    op.drop_table("alerts")
    # ### end Alembic commands ###
